// <auto-generated />
namespace StudentCourses.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserrenamedtoStudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserrenamedtoStudent));
        
        string IMigrationMetadata.Id
        {
            get { return "201802241756418_User renamed to Student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
